FROM node:20-alpine3.19 as base

#stage 1: Building stuff
FROM BASE as builder

WORKDIR /home/build

COPY package*.json .
COPY tsconfig.json .

RUN npm i

COPY src/ src/

RUN npm run build

#stage 2: Runner

FROM base as runner

WORKDIR /home/app

COPY --from=builder /home/build/dist dist/
COPY --from=builder /home/build/package*.json .

RUN npm i --omit=dev

CMD [ "npm","start" ]